/**
 * Copyright (c) Codice Foundation
 *
 * <p>This is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 3 of
 * the License, or any later version.
 *
 * <p>This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details. A copy of the GNU Lesser General Public
 * License is distributed along with this program and can be found at
 * <http://www.gnu.org/licenses/lgpl.html>.
 */
package org.codice.ddf.features.test.config;

import static org.ops4j.pax.exam.CoreOptions.maven;

import java.nio.file.Path;
import java.nio.file.Paths;

import org.codice.ddf.features.test.DependencyVersionResolver;
import org.ops4j.pax.exam.Option;
import org.ops4j.pax.exam.karaf.options.KarafDistributionOption;

public class DistributionOptions {

  public static final Path DEPENDENCY_PROPERTIES_PATH =
      Paths.get("target", "classes", "META-INF", "maven", "dependencies.properties");

  public static Option kernelDistributionOption() {
    return KarafDistributionOption.karafDistributionConfiguration()
        .frameworkUrl(
            maven()
                .groupId("org.codice.ddf")
                .artifactId("kernel")
                .version(DependencyVersionResolver.resolver())
                .type("zip"))
        .unpackDirectory(Paths.get("target", "exam").toFile())
        .useDeployFolder(false);
  }

  /**
   * Copies the dependencies.properties file generated by the maven-dependency-plugin into the test
   * distribution. This is required when using the {@link DependencyVersionResolver}
   */
  public static Option includeDependencyPropertiesFile() {
    return KarafDistributionOption.replaceConfigurationFile(
        "dependencies.properties", DEPENDENCY_PROPERTIES_PATH.toFile());
  }
}
